version: '3.1'

services:
    appwpjson:
        image: malacodajov/wpcentos:1.0
        container_name: app-wp-json
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
           - ./certificates/woo.crt:/etc/ssl/app.crt
           - ./certificates/woo.key:/etc/ssl/app.key
           - ./init.db/:/docker-entrypoint-initdb.d/
           - ./uploads:/opt/app/public/wp-content/uploads/
           - wpjsonpersist:/var/lib/mysql
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: wpdata
           MYSQL_USER: dev
           MYSQL_PASSWORD: dev123
        ports:
           - "3309:3306"
           - "8090:80"
           - "8091:443"
volumes:
    wpjsonpersist:
    