version: '3.1'

services:
    appwpjson:
        image: malacodajov/wpcentos:beta
        container_name: app-wp-json
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
           - ./init.db/:/docker-entrypoint-initdb.d/
           - wpjsonpersist:/var/lib/mysql
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: wpdata
           MYSQL_USER: dev
           MYSQL_PASSWORD: dev123
        ports:
           - "3309:3306"
           - "8090:80"
volumes:
    wpjsonpersist:
    